  #                                #
 #                                  #
#   AdvancedNMotd - ~10.0.0 Release   #
 #                                  #
  #                                #

#Official download link:
#https://www.spigotmc.org/resources/advancednmotd-let-your-motd-smile.58677/

name: AdvancedNMotd
main: ru.namerpro.AdvancedNMotd.Bukkit.Main
author: NamerPRO
version: 10.0.0
load: POSTWORLD
api-version: 1.13
website: https://www.spigotmc.org/resources/advancednmotd-let-your-motd-smile.58677/
description: An awesome advanced server motd changing plugin.
depend: [ProtocolLib]

commands:
  advancedNMotd:
        description: Manages the plugin.
        usage: /<command> [help|reload]